export const homeObjOne = { 
    id:'about',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Lorem Ipsum',
    headline: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../images/vehicle.png'),
    alt: 'Car',
    dark: true,
    dark2:true,
    primary: true,
    darkText: true,
}

export const homeObjTwo = { 
    id:'discover',
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Lorem Ipsum',
    headline: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../images/three.png'),
    alt: 'Three',
    dark: false,
    dark2:true,
    primary: false,
    darkText: false,
}

export const homeObjThree = { 
    id:'services',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Lorem Ipsum',
    headline: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../images/piggy.png'),
    alt: 'Car',
    dark: false,
    dark2:false,
    primary: false,
    darkText: false,
}