export const homeObjOne = { 
    id:'about',
    lightBg: true,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Lorem Ipsum',
    headline: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../images/vehicle.png'),
    alt: 'Car',
    dark: true,
    dark2:true,
    primary: true,
    darkText: false,
}